### PR TITLE
Modified gentx for kentzz001 validator

### PR DESCRIPTION
**Pull request by Kenertlaak**
- gentx Kentzz001™#6153
- modified gentx for kentzz001 validator

### CODE REVIEW

**Comment by Kenertlaak** [comment]
Now I got it right, uhh. 

Sorry again for the mess.

-Kentzz001

**Comment by faddat** [comment]
oh no worries :)

**Comment by Kenertlaak** [comment]
Is there something wrong or what? I mean it's still open and under review.

Thanks.

**Comment by faddat** [comment]
no, working on other things!  won't miss this.

**Pull request merged**
