### PR TITLE
CV add snapshot manager to dig app

### PR DESCRIPTION
**Pull request by chillyvee**
## What is the purpose of the change

dig v3.3.1 and cosmos-sdk v0.46.6 omit the snapshot manager
add it back in

## Brief Changelog

add snapshot manager to cmd/root.go

## Testing and Verifying
Currently broken

```
INF indexed block exents height=4409975 module=txindex
INF completed state snapshot format=2 height=4409975
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe44873]
goroutine 6571 [running]:
github.com/cosmos/iavl.(*nodeDB).incrVersionReaders(0x2cfec78?, 0x20?)
        /home/dig/golang/1.19.3/packages/pkg/mod/github.com/cosmos/iavl@v0.19.4/nodedb.go:943 +0x33
github.com/cosmos/iavl.newExporter(0xc009f74100)
        /home/dig/golang/1.19.3/packages/pkg/mod/github.com/cosmos/iavl@v0.19.4/export.go:46 +0xc8
github.com/cosmos/iavl.(*ImmutableTree).Export(...)
        /home/dig/golang/1.19.3/packages/pkg/mod/github.com/cosmos/iavl@v0.19.4/immutable_tree.go:159
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Export(0xc00e45d368?, 0x2cebe20?)
        /home/dig/cosmos-sdk/store/iavl/store.go:282 +0x52
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Snapshot(0xc000219a20, 0x434a77, {0x2cddc40, 0xc00303abd0})
        /home/dig/cosmos-sdk/store/rootmulti/store.go:742 +0x5bd
github.com/cosmos/cosmos-sdk/snapshots.(*Manager).createSnapshot(0xc000230e10, 0xc8ed66?, 0xc0016c6880?)
        /home/dig/cosmos-sdk/snapshots/manager.go:199 +0xb1
created by github.com/cosmos/cosmos-sdk/snapshots.(*Manager).Create
        /home/dig/cosmos-sdk/snapshots/manager.go:181 +0x2a5
ERR  error="exit status 2" module=cosmovisor
```

### CODE REVIEW

**Comment by chillyvee** [comment]
```func (ndb *nodeDB) incrVersionReaders(version int64) {
        ndb.mtx.Lock() <- crashes here
        defer ndb.mtx.Unlock()
        ndb.versionReaders[version]++
}
```

**Comment by chillyvee** [comment]
Note: Removing snapshot directory to force a new db creation does not resolve the issue

**Comment by faddat** [comment]
hey :)!  this PR crashes?

**Comment by chillyvee** [comment]
> hey :)! this PR crashes?

Yes, need some help to figure out why it explodes.  Sharing my progress :)

**Comment by chillyvee** [comment]
so far the cause found is:
  icahost store has no ndb set

**Comment by chillyvee** [comment]
Root cause is that Dig's icahost store has immutable_tree's ndb *nodedb is set to nil

Snapshot works if iavl doesn't crash on that error.

So 
1) iavl needs a safety patch
2) would be good to determine why dig's icahost doesn't have a nodedb set

**Comment by chillyvee** [comment]
Related PRs:

Prevent newExporter crash if tree.ndb is nil #622
https://github.com/cosmos/iavl/pull/622

fix: snapshot recover from exporter error #13935
https://github.com/cosmos/cosmos-sdk/pull/13935

**Comment by chillyvee** [comment]
Snapshot is tested to work by 

replacing cosmos/iavl with chillyvee/iavl branch `cv_rescue_tree_ndb_nil`

replacing cosmos/cosmos-sdk with chillyvee/cosmos-sdk branch `v0466_snapshot_recover_from_exporter_error`

**Comment by chillyvee** [comment]
goleveldb -> pebbledb restore - OK
pebbledb -> goleveldb restore - Pending

**Comment by chillyvee** [comment]
@faddat - I think the pruning issue is due to icahost not having nodedb configured.

Pruning icahost which does not have a  ndb *nodedb configured is probably what is breaking pruning

Does Dig chain use icahost?  It seems to statesync/snapshot restore just fine without icahost.

**Comment by chillyvee** [comment]
Current snapshot creation/restore testing notes published here:

https://github.com/notional-labs/dig/issues/426

**Comment by faddat** [comment]
amazing dude

**Pull request merged**
